---
- name: Init gitlab
  hosts: all
  tasks:
    - name: Init gitlab
      shell: |
        curl -L --output /usr/local/bin/gitlab-runner "https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64"
        chmod +x /usr/local/bin/gitlab-runner
        gitlab-runner install --user=root --working-directory=/root
        gitlab-runner start
        export REGISTRATION_TOKEN="{{ TOKEN }}"
        gitlab-runner register --non-interactive  --url https://gitlab.com/ --registration-token $REGISTRATION_TOKEN  --executor "shell" --description "k8s-master" --tag-list "ubuntu2004-lab"
        rm -rf /home/gitlab-runner/.bash_logout
      when: 
        - ansible_facts['hostname'] == 'master'
    