apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db
spec:
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: tgc101/lab-mysql:0.1
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: tibame
          - name: MYSQL_DATABASE
            value: tibame
  selector:
    matchLabels:
      app: db

---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  ports:
    - targetPort: 3306
      port: 3306
  selector:
    app: db
